### ISSUE TITLE
Support for `@constinferred_broken` [Feature Req.]

### ISSUE THREAD

**Issue by agerlach** [Jutho/TestExtras.jl#3]
I often finding myself wanting to track cases in my test where inference fails as a broken test. This doesn't currently look possible.

**Comment by Jutho** [comment]
Feel free to implement something like this. I am happy to accept PRs, but won't have much time for this any time soon.

**Comment by agerlach** [comment]
Sounds good. I have not written any macros before, but looking over the source, I think I could add this with very minimal changes.
